### ISSUE TITLE
更新ck的请求问题

### ISSUE THREAD

**Issue by yiyule10** [zia142857/document#1]
[更新ck](https://github.com/zia142857/document/blob/main/%E9%9D%92%E9%BE%99openAPI%E9%9D%9E%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3.md#%E6%9B%B4%E6%96%B0ck)，这里可以放一个实例吗？我按照这个填写进去，报出错误`AxiosError: Request failed with status code 400`
希望大佬解答

**Comment by yiyule10** [comment]
变量名错了，已经解决

**Comment by zia142857** [comment]
不是大佬哈，孩子不懂事，随便写的

**Comment by yiyule10** [comment]
> 不是大佬哈，孩子不懂事，随便写的

2.11版本之后的青龙openapi，变了，把`_id`改成了`id`
希望能标注一下版本

**Comment by zia142857** [comment]
> > 不是大佬哈，孩子不懂事，随便写的
> 
> 2.11版本之后的青龙openapi，变了，把`_id`改成了`id` 希望能标注一下版本

好的
